name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building the site..." # Aquí pones tu comando de construcción si es necesario

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: '.' # Cambia esto a tu carpeta de salida si es necesario

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: '.' # Cambia esto a tu carpeta de salida si es necesario
